### ISSUE TITLE
Online/First Half/Second Half/Campus Filters

### ISSUE THREAD

**Issue by j-r-wolfe** [FlexScheduler/FlexScheduler#7]
On our main page of the GUI I think we could split the long div of the min/max credit selections to fit in the online/first half/second half filters, which could be listed as check boxes (and maybe include campus here as a drop-down or with the "Select Semester" drop-down).

We would need to store this information client-side.

**Comment by jamesa1551** [comment]
Online
Campus
first and second half for 8 weeks classes
